[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-10_x"]

[phases.install]
cmds = ["cd api && npm ci --no-audit --no-fund"]

[phases.build]
cmds = ["cd api && npx prisma generate && npm run build"]

[start]
cmd = "cd api && npx prisma migrate deploy && node .next/standalone/server.js"
