server {
    listen ${PORT};
    server_name _;
    root /usr/share/nginx/html;
    index index.html;


    location / {
        try_files $uri $uri/ $uri.html =404;
    }


    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }


    error_page 404 /index.html;
}
